### ISSUE TITLE
Remove copy of the teamviewer repo key

### ISSUE THREAD

**Issue by iluminat23** [zhan-kunbus/files4elbe#1]
Currently a copy of the teamviewer repo key is used in the armhf-revpi.xml file.
https://github.com/zhan-kunbus/files4elbe/blob/a7b5570beee5bb6b4ea8a6a9b21446ca298710ca/armhf-revpi.xml#L109

If the key changes, building the image will fail. Then the new key needs to be provided. A solution where (always) the correct key is provided is needed.

**Comment by zhan-kunbus** [comment]
This should be another issue we need to ask the teamviewer company to do.

**Comment by iluminat23** [comment]
Could you create a ticket for that?

**Comment by zhan-kunbus** [comment]
Here it is: https://kunbus-gmbh.atlassian.net/browse/REVPI-1427
