### ISSUE TITLE
A copy of the revpi repo key is used.

### ISSUE THREAD

**Issue by iluminat23** [zhan-kunbus/files4elbe#2]
Using a copy of the revpi-repo key is a bad idea. (See the following issue as well: https://github.com/zhan-kunbus/files4elbe/issues/1)

https://github.com/zhan-kunbus/files4elbe/blob/a7b5570beee5bb6b4ea8a6a9b21446ca298710ca/armhf-revpi.xml#L101

**Comment by zhan-kunbus** [comment]
This key is needed to install the packages from revpi repository, in which all packages are signed with the corresponding private key.
 But it should be put in a permanent location, e.g http://packages.revolutionpi.de/ or http://www.kunbus.com

**Comment by iluminat23** [comment]
Could you create a ticket for that?

**Comment by zhan-kunbus** [comment]
https://kunbus-gmbh.atlassian.net/browse/REVPI-1428
