### ISSUE TITLE
Don't install the ubuntu keyring in the initvm

### ISSUE THREAD

**Issue by iluminat23** [zhan-kunbus/files4elbe#3]
We are not using any packages from the ubuntu repo, so we don't need to install the ubuntu keyring.
https://github.com/zhan-kunbus/files4elbe/blob/a7b5570beee5bb6b4ea8a6a9b21446ca298710ca/armhf-revpi.xml#L56

**Comment by zhan-kunbus** [comment]
I will test it

**Comment by zhan-kunbus** [comment]
https://kunbus-gmbh.atlassian.net/browse/REVPI-1432
